# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: push

jobs:
  build-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install -g pnpm
      - run: pnpm install
      - run: ./node_modules/.bin/nx run nest-consul:build
      - run: cd dist/packages/nest-consul & ls -l
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}

#  publish-npm:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#          registry-url: https://registry.npmjs.org/
#      - run: cd dist/packages/nest-consul
#      - run: ls -l
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
